import sgbd

if __name__ == "__main__":
    op = 5
    while(op != 0):
        print (op)
        print ('---------------- Menu ----------------')
        print ('Digite 1 para inserir um dado no banco')
        print ('Digite 2 para atualizar um dado no banco')
        print ('Digite 3 para remover um dado no banco')
        print ('Digite 4 para selecionar um dado no banco')
        print ('Digite 0 para sair do Sistema de Atualizacoes intergalaticos do interior de Quixeramobim')

        op = raw_input("Qual opcao voce escolhe? ")

        if op == '1':
            #INSERIR
            print ('Em qual tabela? Voce precisa digitar o nome exato da tabela. VOCE PRECISA DIGITAR O NOME EXATO DA TABELA')
            print('- EMPREGADO')
            print('- TELEFONES')
            print('- PASSAGEIRO')
            print('- ASSENTO')
            print('- PASSAGEMPASSAGEIRO')
            print('- MODELO')
            print('- AVIAO')
            print('- COPILOTO')
            print('- COMISSARIO')
            print('- VOA')
            print('- GRATIFICACAO')
            print('- VIAGEM')
            print('- COMPART')
            print('- RECEBE')
            print('- PARTICIPA')
            print('-------------- LEMBRE DE DIGITAR O NOME EXATO DE TABELAS, COLUNAS -------------')
            print('-------------- Essas sao as opcoes de tabela -------------')
            sql = raw_input("Digite seu script\n ")
            sgbd.insert(sql)
        elif op == '2':
            # ATUALIZAR
            print ('Em qual tabela? Voce precisa digitar o nome exato da tabela. VOCE PRECISA DIGITAR O NOME EXATO DA TABELA')
            print('- EMPREGADO')
            print('- TELEFONES')
            print('- PASSAGEIRO')
            print('- ASSENTO')
            print('- PASSAGEMPASSAGEIRO')
            print('- MODELO')
            print('- AVIAO')
            print('- COPILOTO')
            print('- COMISSARIO')
            print('- VOA')
            print('- GRATIFICACAO')
            print('- VIAGEM')
            print('- COMPART')
            print('- RECEBE')
            print('- PARTICIPA')
            print('-------------- LEMBRE DE DIGITAR O NOME EXATO DE TABELAS, COLUNAS -------------')
            print('-------------- Essas sao as opcoes de tabela -------------')
            sql = raw_input("Digite seu script\n ")
            sgbd.update(sql)
        elif op == '3':
            # REMOVER
            print ('Em qual tabela? Voce precisa digitar o nome exato da tabela. VOCE PRECISA DIGITAR O NOME EXATO DA TABELA')
            print('- EMPREGADO')
            print('- TELEFONES')
            print('- PASSAGEIRO')
            print('- ASSENTO')
            print('- PASSAGEMPASSAGEIRO')
            print('- MODELO')
            print('- AVIAO')
            print('- COPILOTO')
            print('- COMISSARIO')
            print('- VOA')
            print('- GRATIFICACAO')
            print('- VIAGEM')
            print('- COMPART')
            print('- RECEBE')
            print('- PARTICIPA')
            print('-------------- LEMBRE DE DIGITAR O NOME EXATO DE TABELAS, COLUNAS -------------')
            print('-------------- Essas sao as opcoes de tabela -------------')
            sql = raw_input("Digite seu script\n ")
            sgbd.delete(sql)
        elif op == '4':
            # SELECIONAR
            print ('Em qual tabela? Voce precisa digitar o nome exato da tabela. VOCE PRECISA DIGITAR O NOME EXATO DA TABELA')
            print('- EMPREGADO')
            print('- TELEFONES')
            print('- PASSAGEIRO')
            print('- ASSENTO')
            print('- PASSAGEMPASSAGEIRO')
            print('- MODELO')
            print('- AVIAO')
            print('- COPILOTO')
            print('- COMISSARIO')
            print('- VOA')
            print('- GRATIFICACAO')
            print('- VIAGEM')
            print('- COMPART')
            print('- RECEBE')
            print('- PARTICIPA')
            print('-------------- LEMBRE DE DIGITAR O NOME EXATO DE TABELAS, COLUNAS -------------')
            print('-------------- Essas sao as opcoes de tabela -------------')
            table = raw_input("Qual sua opcao de tabela?")
            filter_column = raw_input("A partir de qual coluna devemos selecionar? ")
            filter = raw_input("E qual deve ser o valor dessa coluna? ")
            sgbd.select(table, filter_column, filter)
        else:
            print ('Bye')
            exit()
