import sgbd

if __name__ == "__main__":
    print ('---------------- Menu ----------------')
    print ('Digite 1 para inserir um dado no banco')
    print ('Digite 2 para atualizar um dado no banco')
    print ('Digite 3 para remover um dado no banco')
    print ('Digite 4 para selecionar um dado no banco')
    print ('Digite 0 para sair do Sistema de Atualizacoes intergalaticos do interior de Quixeramobim')

    op = raw_input("Qual opcao voce escolhe? ")

    if op == '1':
        #INSERIR
        print ('Em qual tabela? Você precisa digitar o nome exato da tabela. VOCE PRECISA DIGITAR O NOME EXATO DA TABELA')
        print('- EMPREGADO')
        print('- TELEFONES')
        print('- PASSAGEIRO')
        print('- ASSENTO')
        print('- PASSAGEMPASSAGEIRO')
        print('- MODELO')
        print('- AVIAO')
        print('- COPILOTO')
        print('- COMISSARIO')
        print('- VOA')
        print('- GRATIFICACAO')
        print('- VIAGEM')
        print('- COMPART')
        print('- RECEBE')
        print('- PARTICIPA')
        print('-------------- Essas sao as opcoes de tabela -------------')
        table = raw_input("Qual sua opcao?")
    elif op == '2':
        # ATUALIZAR
        print ('Em qual tabela? Você precisa digitar o nome exato da tabela. VOCE PRECISA DIGITAR O NOME EXATO DA TABELA')
        print('- EMPREGADO')
        print('- TELEFONES')
        print('- PASSAGEIRO')
        print('- ASSENTO')
        print('- PASSAGEMPASSAGEIRO')
        print('- MODELO')
        print('- AVIAO')
        print('- COPILOTO')
        print('- COMISSARIO')
        print('- VOA')
        print('- GRATIFICACAO')
        print('- VIAGEM')
        print('- COMPART')
        print('- RECEBE')
        print('- PARTICIPA')
        print('-------------- Essas sao as opcoes de tabela -------------')
        table = raw_input("Qual sua opcao?")
    elif op == '3':
        # REMOVER
        print ('Em qual tabela? Você precisa digitar o nome exato da tabela. VOCE PRECISA DIGITAR O NOME EXATO DA TABELA')
        print('- EMPREGADO')
        print('- TELEFONES')
        print('- PASSAGEIRO')
        print('- ASSENTO')
        print('- PASSAGEMPASSAGEIRO')
        print('- MODELO')
        print('- AVIAO')
        print('- COPILOTO')
        print('- COMISSARIO')
        print('- VOA')
        print('- GRATIFICACAO')
        print('- VIAGEM')
        print('- COMPART')
        print('- RECEBE')
        print('- PARTICIPA')
        print('-------------- Essas sao as opcoes de tabela -------------')
        table = raw_input("Qual sua opcao?")
    elif op == '4':
        # SELECIONAR
        print ('Em qual tabela? Você precisa digitar o nome exato da tabela. VOCE PRECISA DIGITAR O NOME EXATO DA TABELA')
        print('- EMPREGADO')
        print('- TELEFONES')
        print('- PASSAGEIRO')
        print('- ASSENTO')
        print('- PASSAGEMPASSAGEIRO')
        print('- MODELO')
        print('- AVIAO')
        print('- COPILOTO')
        print('- COMISSARIO')
        print('- VOA')
        print('- GRATIFICACAO')
        print('- VIAGEM')
        print('- COMPART')
        print('- RECEBE')
        print('- PARTICIPA')
        print('-------------- Essas sao as opcoes de tabela -------------')
        table = raw_input("Qual sua opcao?")
        filter_column = raw_input("Voce quer filtrar por qual coluna?")
        filter = raw_input("Por qual voce quer selecionar? Qual sera seu filtro")
        sgbd.select(table, filter_column, filter)
    else:
        print ('Bye')
        exit()